openapi: 3.0.3
info:
  version: 1.0.0
  title: Sample API
  description: >
    This is a basic example of an OpenAPI YAML file for a sample API.

  contact:
    name: John Doe
    email: john.doe@example.com
  license:
    name: MIT License
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: Users
    description: Operations related to users
  - name: Products
    description: Operations related to products
servers:
  - url: 'https://api.example.com/v1'
    description: Production server
  - url: 'https://api.staging.example.com/v1'
    description: Staging server
paths:
  /users:
    get:
      tags:
        - Users
      summary: Get all users
      operationId: getAllUsers
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
    post:
      tags:
        - Users
      summary: Create a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
  /products:
    get:
      tags:
        - Products
      summary: Get all products
      operationId: getAllProducts
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    price:
                      type: number
